trigger:
  - main

pool:
  name: Local

variables:
  - name: AZURE_SUBSCRIPTION
    value: "Azure-DevOps-Connection"
  - name: TF_STATE_STORAGEACCOUNT_RESOURCEGROUP_NAME
    value: "GeekyMon2Storage"
  - name: TF_STORAGE_ACCOUNT_NAME
    value: "geekymon2storageaccount"
  - name: TF_STORAGE_ACCOUNT_CONTAINER_NAME
    value: "geekymon2-storage-container"
  - name: TF_KEY
    value: "terraform.tfstate"

stages:
  - stage: Terraform_Deployment
    displayName: Terraform_Install
    jobs:
      - job: Terraform
        displayName: "Terraform"
        steps:
          ### This is for Testing Only ####
          # - task: CmdLine@2
          #   inputs:
          #     script: |
          #       echo $(Build.SourcesDirectory)

          - task: TerraformInstaller@2
            displayName: install terraform
            inputs:
              terraformVersion: "latest"

          - task: TerraformCLI@0
            displayName: "check terraform version"
            inputs:
              command: version

          - task: TerraformCLI@0
            displayName: "Terraform Init"
            inputs:
              command: "init"
              backendType: "azurerm"
              workingDirectory: $(Build.SourcesDirectory)
              backendServiceArm: ${{ variables.AZURE_SUBSCRIPTION }}
              backendAzureRmResourceGroupName: ${{ variables.TF_STATE_STORAGEACCOUNT_RESOURCEGROUP_NAME }}
              backendAzureRmStorageAccountName: ${{ variables.TF_STORAGE_ACCOUNT_NAME }}
              backendAzureRmContainerName: ${{ variables.TF_STORAGE_ACCOUNT_CONTAINER_NAME }}
              backendAzureRmKey: ${{ variables.TF_KEY }}

          - task: TerraformCLI@0
            displayName: "Terraform Validate"
            inputs:
              command: "validate"
              backendType: "azurerm"
              workingDirectory: $(Build.SourcesDirectory)
              backendServiceArm: ${{ variables.AZURE_SUBSCRIPTION }}

          - task: TerraformCLI@0
            displayName: "Terraform Plan"
            inputs:
              command: "plan"
              backendType: "azurerm"
              workingDirectory: $(Build.SourcesDirectory)
              environmentServiceName: ${{ variables.AZURE_SUBSCRIPTION }}

          - task: TerraformCLI@0
            displayName: "Terraform Apply"
            inputs:
              command: "apply"
              backendType: "azurerm"
              workingDirectory: $(Build.SourcesDirectory)
              environmentServiceName: ${{ variables.AZURE_SUBSCRIPTION }}

      - job: Deploy
        displayName: "Deploy"
        dependsOn:
          - Terraform
        steps:
          - task: DownloadPackage@1
            displayName: "Download Artifact"
            inputs:
              packageType: "upack"
              feed: "Tasker/tasker"
              definition: "tasker"
              version: "1.0.25"
              downloadPath: "$(System.DefaultWorkingDirectory)/artifact"

          - task: AzureRmWebAppDeployment@4
            displayName: "Deploy to Azure"
            inputs:
              ConnectionType: "AzureRM"
              azureSubscription: ${{ variables.AZURE_SUBSCRIPTION }}
              appType: "webAppLinux"
              WebAppName: "tasker-linux-web-app"
              packageForLinux: "$(System.DefaultWorkingDirectory)/artifact"
