trigger:
  - main

pool:
  name: Local

variables:
  TF_WORKING_DIRECTORY: "terraform"
  AZURE_SUBSCRIPTION: "Azure-DevOps-Connection"

stages:
  - stage: Checkout_Install
    displayName: Terraform_Install
    jobs:
      - job: Terraform
        displayName: "Terraform"
        steps:
          - task: TerraformInstaller@2
            displayName: install terraform
            inputs:
              terraformVersion: "latest"

          - task: TerraformCLI@0
            displayName: "check terraform version"
            inputs:
              command: version

          - task: CmdLine@2
            inputs:
              script: |
                echo $(Build.SourcesDirectory)/$(Build.Repository.Name)

          - task: TerraformCLI@0
            displayName: "Terraform Init"
            inputs:
              command: "init"
              workingDirectory: $(Build.SourcesDirectory)

          - task: TerraformCLI@0
            displayName: "Terraform Validate"
            inputs:
              command: "validate"
              workingDirectory: $(Build.SourcesDirectory)

          - task: TerraformCLI@0
            displayName: "Terraform Plan"
            inputs:
              command: "plan"
              workingDirectory: $(Build.SourcesDirectory)
              additionalArgs: "-out=tfplan"

          - task: TerraformCLI@0
            displayName: "Terraform Apply"
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
            inputs:
              command: "apply"
              workingDirectory: $(Build.SourcesDirectory)
              additionalArgs: "-auto-approve tfplan"
