trigger:
  - main

pool:
  name: Local

variables:
  - group: "AZURE_SP_TERRAFORM"
  - name: TF_STATE_STORAGEACCOUNT_RESOURCEGROUP_NAME
    value: "GeekyMon2Storage"
  - name: TF_STORAGE_ACCOUNT_NAME
    value: "geekymon2storageaccount"
  - name: TF_STORAGE_ACCOUNT_CONTAINER_NAME
    value: "geekymon2-storage-container"
  - name: TF_KEY
    value: "terraform.tfstate"

stages:
  - stage: Terraform_Deployment
    displayName: Terraform_Install
    jobs:
      - job: Terraform
        displayName: "Terraform"
        steps:
          ### This is for Testing Only ####
          # - task: CmdLine@2
          #   inputs:
          #     script: |
          #       echo $(Build.SourcesDirectory)

          - task: TerraformInstaller@2
            displayName: install terraform
            inputs:
              terraformVersion: "latest"

          - task: TerraformCLI@0
            displayName: "check terraform version"
            inputs:
              command: version

          - task: TerraformCLI@0
            displayName: "Terraform Init"
            inputs:
              command: "init"
              backendType: "azurerm"
              workingDirectory: $(Build.SourcesDirectory)
              backendServiceArm: ${{ variables.AZURE_SUBSCRIPTION }}
              backendAzureRmResourceGroupName: ${{ variables.TF_STATE_STORAGEACCOUNT_RESOURCEGROUP_NAME }}
              backendAzureRmStorageAccountName: ${{ variables.TF_STORAGE_ACCOUNT_NAME }}
              backendAzureRmContainerName: ${{ variables.TF_STORAGE_ACCOUNT_CONTAINER_NAME }}
              backendAzureRmKey: ${{ variables.TF_KEY }}
            env:
              ARM_SUBSCRIPTION_ID: ${{ variables.AZURE_SUBSCRIPTION }}
              ARM_CLIENT_ID: ${{ variables.AZURE_SERVICE_PRINCIPAL_ID }}
              ARM_CLIENT_SECRET: ${{ variables.AZURE_SERVICE_PRINCIPAL_PASSWORD }}
              ARM_TENANT_ID: ${{ variables.AZURE_TENANT_ID }}

          - task: TerraformCLI@0
            displayName: "Terraform Validate"
            inputs:
              command: "validate"
              backendType: "azurerm"
              workingDirectory: $(Build.SourcesDirectory)
              backendServiceArm: ${{ variables.AZURE_SUBSCRIPTION }}

          - task: TerraformCLI@0
            displayName: "Terraform Plan"
            inputs:
              command: "plan"
              backendType: "azurerm"
              workingDirectory: $(Build.SourcesDirectory)
              backendServiceArm: ${{ variables.AZURE_SUBSCRIPTION }}

          - task: TerraformCLI@0
            displayName: "Terraform Apply"
            inputs:
              command: "apply"
              backendType: "azurerm"
              workingDirectory: $(Build.SourcesDirectory)
              backendServiceArm: ${{ variables.AZURE_SUBSCRIPTION }}

      - job: Deploy
        displayName: "Deploy"
        dependsOn:
          - Terraform
        steps:
          - task: DownloadPackage@1
            displayName: "Download Artifact"
            inputs:
              packageType: "upack"
              feed: "tasker"
              definition: "Tasker"
              version: "latest"
              downloadPath: "$(System.DefaultWorkingDirectory)/artifact"
